package com.apm.echart.dao.client;

import com.apm.echart.dao.model.UserT;
import com.apm.echart.dao.model.UserTExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

/**
 * 自动化生成的接口。
 * @author yanghaitao
 *
 */
public interface UserTMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_t
     *
     * @mbggenerated Tue Aug 02 14:08:50 CST 2016
     */
    int countByExample(UserTExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_t
     *
     * @mbggenerated Tue Aug 02 14:08:50 CST 2016
     */
    int deleteByExample(UserTExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_t
     *
     * @mbggenerated Tue Aug 02 14:08:50 CST 2016
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_t
     *
     * @mbggenerated Tue Aug 02 14:08:50 CST 2016
     */
    int insert(UserT record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_t
     *
     * @mbggenerated Tue Aug 02 14:08:50 CST 2016
     */
    int insertSelective(UserT record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_t
     *
     * @mbggenerated Tue Aug 02 14:08:50 CST 2016
     */
    List<UserT> selectByExample(UserTExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_t
     *
     * @mbggenerated Tue Aug 02 14:08:50 CST 2016
     */
    UserT selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_t
     *
     * @mbggenerated Tue Aug 02 14:08:50 CST 2016
     */
    int updateByExampleSelective(@Param("record") UserT record, @Param("example") UserTExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_t
     *
     * @mbggenerated Tue Aug 02 14:08:50 CST 2016
     */
    int updateByExample(@Param("record") UserT record, @Param("example") UserTExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_t
     *
     * @mbggenerated Tue Aug 02 14:08:50 CST 2016
     */
    int updateByPrimaryKeySelective(UserT record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_t
     *
     * @mbggenerated Tue Aug 02 14:08:50 CST 2016
     */
    int updateByPrimaryKey(UserT record);
}